import { getAuthToken } from "@frontend/authentication-view";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "@frontend/toast-context";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  await getAuthToken();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer>{children}</ToastContainer>
      </body>
    </html>
  );
}
