import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "@frontend/toast-context";
import { Navbar } from "../components/navbar/navbar";
import { ModalContainer } from "@frontend/modal-context";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer>
          <ModalContainer>
            <Navbar />
            <div className="pt-16 px-5">{children}</div>
          </ModalContainer>
        </ToastContainer>
      </body>
    </html>
  );
}
